from django.urls import path
from .views import *


urlpatterns = [
    path("users/", UsersListView.as_view(), name="users-list"),
    path("create/", CreateUserView.as_view()),
    path("login/", LoginView.as_view()),
    path("change-password/", ChangePasswordView.as_view()),
    path("forgot-password/", ForgotPasswordView.as_view()),
    path("reset-password/<int:uid>/<str:token>/", ResetPasswordView.as_view()),
    path("refresh/token/", CustomTokenRefreshView.as_view(), name="token_refresh"),
    path("facilities/", FacilityListCreateView.as_view(), name="facility-list-create"),
    path("facilities/<str:pk>/", FacilityRetrieveUpdateDeleteView.as_view(), name="facility-detail"),
    path("branches/", BranchListCreateView.as_view(), name="branch-list-create"),
    path("branches/<str:pk>/", BranchRetrieveUpdateDeleteView.as_view(), name="branch-detail"),
    path('residents/', ResidentListCreateView.as_view(), name='resident_list_create'),
    path('residents/<int:resident_id>/', ResidentRetrieveUpdateDeleteView.as_view(), name='resident_detail'),
    path("branch-managers/", BranchManagerListCreateView.as_view()),
    path("branch-managers/<uuid:pk>/", BranchManagerDetailView.as_view()),
    path("my-branch/residents/", ResidentsInMyBranchView.as_view()),
    path("care/categories/", CareCategoryView.as_view()),
    path("care/items/", CareItemView.as_view()),
    path("care/chart/", ResidentDailyChartView.as_view()),
    path("care/chart/<uuid:resident_id>/<str:date>/", ResidentDailyChartDetailView.as_view()),
    path("care/charts/", ResidentDailyChartListView.as_view()),
    path("care/chart/review/<uuid:chart_id>/", ReviewResidentDailyChartView.as_view()),
    path("late-permissions/", LateSubmissionPermissionListCreateView.as_view(), name="late-permission-list"),
    path("late-permissions/<uuid:pk>/", LateSubmissionPermissionDetailView.as_view(), name="late-permission-detail"),
    path("vitals/", VitalListCreateView.as_view(), name="vital-list-create"),
    path("vitals/<uuid:pk>/", VitalDetailView.as_view(), name="vital-detail"),
    path("vitals/<uuid:pk>/review/", VitalReviewView.as_view(), name="vital-review"),
    path("updates/", UpdateListCreateView.as_view(), name="update-list-create"),
    path("updates/<uuid:pk>/", UpdateDetailView.as_view(), name="update-detail"),
    path("updates/<uuid:pk>/review/", UpdateReviewView.as_view(), name="update-review"),
    path("appointments/", AppointmentListCreateView.as_view(), name="appointment-list-create"),
    path("appointments/<uuid:pk>/", AppointmentDetailView.as_view(), name="appointment-detail"),
    path("leave-requests/", LeaveRequestListCreateView.as_view(), name="leave-request-list-create"),
    path("leave-requests/<uuid:pk>/", LeaveRequestDetailView.as_view(), name="leave-request-detail"),
    path("leave-requests/<uuid:pk>/review/", LeaveRequestReviewView.as_view(), name="leave-request-review"),
    path("grocery-requests/", GroceryRequestListCreateView.as_view(), name="grocery-request-list"),
    path("grocery-requests/<uuid:pk>/", GroceryRequestDetailView.as_view(), name="grocery-request-detail"),
    path("grocery-requests/<uuid:pk>/review/", GroceryRequestReviewView.as_view(), name="grocery-request-review"),
    path("utilities/", UtilityRequestListCreateView.as_view(), name="utility-list-create"),
    path("utilities/<uuid:pk>/", UtilityRequestDetailView.as_view(), name="utility-detail"),
    path("utilities/<uuid:pk>/action/", UtilityRequestActionView.as_view(), name="utility-action"),
    path("assessments/", AssessmentListCreateView.as_view(), name="assessment-list-create"),
    path("assessments/<uuid:pk>/", AssessmentDetailView.as_view(), name="assessment-detail"),
    path("sleep-patterns/", SleepPatternListCreateView.as_view(), name="sleep-pattern-list"),
    path("sleep-patterns/<uuid:pk>/", SleepPatternDetailView.as_view(), name="sleep-pattern-detail"),

]
